### ISSUE TITLE
Invalid signature when creating orders in negative risk market

### ISSUE THREAD

**Issue by dmitry-dzyuba-uinno** [Polymarket/py-clob-client#79]
## Overview
When trying to create an order in negative risk market, it gives me an error "invalid signature", creating orders for non-negative risk markets works fine.

## Code sample

```python
#...
resp = client.create_and_post_order(OrderArgs(
    price=0.01,
    size=5.0,
    side=BUY,
    token_id="23879627426961662812922169694268707374662971136118079896087093103802667054172"
))
```

## Response
```
Traceback (most recent call last):
  File "/var/www/html/scripts/py-clob-client/create_and_post_order.py", line 32, in <module>
    resp = client.create_and_post_order(OrderArgs(
  File "/var/www/html/scripts/py-clob-client/py_clob_client/client.py", line 314, in create_and_post_order
    return self.post_order(ord)
  File "/var/www/html/scripts/py-clob-client/py_clob_client/client.py", line 305, in post_order
    return post("{}{}".format(self.host, POST_ORDER), headers=headers, data=body)
  File "/var/www/html/scripts/py-clob-client/py_clob_client/http_helpers/helpers.py", line 48, in post
    return request(endpoint, POST, headers, data)
  File "/var/www/html/scripts/py-clob-client/py_clob_client/http_helpers/helpers.py", line 41, in request
    raise PolyApiException(resp)
py_clob_client.exceptions.PolyApiException: PolyApiException[status_code=400, error_message={'error': 'invalid signature'}]
```

I was initially using version v0.11.0, but it's same on v0.16.0

**Comment by zlandme** [comment]
I had the same question, how can I resolve this question？

**Comment by dmitry-dzyuba-uinno** [comment]
@zlandme I actually figured this out, the official example doesn't include this, but in recent versions you need to actually pass a parameter to the function if it's negative risk market or not. Here is an example: 

```python
ord = client.create_order(OrderArgs(
    price=args.price,
    size=args.size,
    side=args.side,
    token_id=args.token_id,
    expiration=args.expiration
), PartialCreateOrderOptions(
    neg_risk=args.neg_risk
))

resp = client.post_order(ord, order_type)
```

**Comment by zlandme** [comment]
> @zlandme I actually figured this out, the official example doesn't include this, but in recent versions you need to actually pass a parameter to the function if it's negative risk market or not. Here is an example:
> 
> ```python
> ord = client.create_order(OrderArgs(
>     price=args.price,
>     size=args.size,
>     side=args.side,
>     token_id=args.token_id,
>     expiration=args.expiration
> ), PartialCreateOrderOptions(
>     neg_risk=args.neg_risk
> ))
> 
> resp = client.post_order(ord, order_type)
> ```

YEAH, you are right, It solved the problem of wrong signature, but I got a new problem,  when I create_and_post order, it give me error "PolyApiException[status_code=400, error_message={'error': 'not enough balance / allowance'}]", I have done the approve, and there are funds in my account, and I can get the fund with my address in the collateral contract address.  how can I resolve this question？

**Comment by vince-gt** [comment]
I'm having the same problem:
`py_clob_client.exceptions.PolyApiException: PolyApiException[status_code=400, error_message={'error': 'invalid signature'}]
`
Tried with Python 3.12.3 then tried Python 3.9.10. negRisk true or false does not matter. Using the py-clob-client v0.17.5.
Tried rolling back a few versions with:
`pip install --force-reinstall -v "py-clob-client==0.xx.x"` 
No luck.
@dmitry-dzyuba-uinno  How did you resolve the invalid signature problem?

**Comment by vince-gt** [comment]
> > @zlandme I actually figured this out, the official example doesn't include this, but in recent versions you need to actually pass a parameter to the function if it's negative risk market or not. Here is an example:
> > ```python
> > ord = client.create_order(OrderArgs(
> >     price=args.price,
> >     size=args.size,
> >     side=args.side,
> >     token_id=args.token_id,
> >     expiration=args.expiration
> > ), PartialCreateOrderOptions(
> >     neg_risk=args.neg_risk
> > ))
> > 
> > resp = client.post_order(ord, order_type)
> > ```
> 
> @dmitry-dzyuba-uinno YEAH, you are right, It solved the problem of wrong signature, but I got a new problem, when I create_and_post order, it give me error "PolyApiException[status_code=400, error_message={'error': 'not enough balance / allowance'}]", I have done the approve, and there are funds in my account, and I can get the fund with my address in the collateral contract address. how can I resolve this question？

Have you tried setting the token allowances as [described in the read me](https://github.com/Polymarket/py-clob-client/blob/main/README.md)? This [script](https://gist.github.com/poly-rodr/44313920481de58d5a3f6d1f8226bd5e) fixed it for me. I had to make some changes to get it to run though. 
getTransactionCount -> get_transaction_count
buildTransaction -> build_transaction
rawTransaction -> raw_transaction

**Comment by vince-gt** [comment]
Got this working with help from Isulls50 on Discord.
**"as a Python moron like countless above, it should be pinned that 'funder=' should be the browser Polymarket Wallet address in the top right under your profile name, NOT YOUR METAMASK! This was the solution to 'invalid signature' for me and i would bet thousands that it's what other people are messing up too"**
https://discord.com/channels/710897173927297116/782024576275447848/1267323493209342073

**Comment by ben0x01** [comment]
Who solve the problem with - "py_clob_client.exceptions.PolyApiException: PolyApiException[status_code=400, error_message={'error': 'not enough balance / allowance'}]"?

I try to sell my positions but gett error

**Comment by hsz0403** [comment]
same as [ben0x01](https://github.com/ben0x01)

**Comment by ben0x01** [comment]
Bro, sometimes the library is stupid :D 
Wait and restart use your script. I really cannot to understand why it's help, but it work)

**Comment by theo-wq** [comment]
hi i have the same probleme but how do you import the "PartialCreateOrderOptions" Thanks a lot

**Comment by vince-gt** [comment]
You will likely get a quicker response on Discord https://discord.com/channels/710897173927297116/782024576275447848

**Comment by lucashhan** [comment]
@gaurav-gupta ,Yes I also met this problem after adding the PartialCreateOrderOptions

**Comment by TallJasonPDX** [comment]
Thanks for this call out and solution!

**Comment by elchananvol** [comment]
for me the problem was solved with:
```python 
    rpc_url = 'https://polygon-rpc.com'  # Polygon rpc url
    web3 = Web3(Web3.HTTPProvider(rpc_url))
    nonce = web3.eth.get_transaction_count(pub_key)
    creds = client.create_or_derive_api_creds(nonce)
```

**Comment by Maxim-Mazurok** [comment]
I have resolved this issue by using funder/public-key/POLYMARKET_PROXY_ADDRESS from the profile (you can see it in the URL when you open your polymarket profile) as opposed to the USDC address that was used to top up my balance. This was pretty misleading in the code snippet from docs:
> POLYMARKET_PROXY_ADDRESS: str = '' #This is the address you deposit/send USDC to to FUND your Polymarket account.

I am 100% certain that it is NOT the USDC address that used to fund my account, I checked in transactions, and also checked when clicking "deposit" button in polymarket, it shows different address than the one displayed on the top right, aka profile address.

Hope this helps!

**Comment by Mugen0** [comment]
I have the signature thing figured out for my case.
I used chain_id=AMOY as examples goes but it's actrually Testnet.
Use chain_id=137 instead.

**Comment by iiosenov** [comment]
> I have resolved this issue by using funder/public-key/POLYMARKET_PROXY_ADDRESS from the profile (you can see it in the URL when you open your polymarket profile) as opposed to the USDC address that was used to top up my balance. This was pretty misleading in the code snippet from docs:
> 
> > POLYMARKET_PROXY_ADDRESS: str = '' #This is the address you deposit/send USDC to to FUND your Polymarket account.
> 
> I am 100% certain that it is NOT the USDC address that used to fund my account, I checked in transactions, and also checked when clicking "deposit" button in polymarket, it shows different address than the one displayed on the top right, aka profile address.
> 
> Hope this helps!

That solved it for me. Initially, I used the deposit address because I had not seen any other address in the Polymarket UI. However, watching the URL bar closely while browsing to my profile, I was able to spot the "funder" address in the URL bar.

**Comment by sharathnirmala16** [comment]
> I have resolved this issue by using funder/public-key/POLYMARKET_PROXY_ADDRESS from the profile (you can see it in the URL when you open your polymarket profile) as opposed to the USDC address that was used to top up my balance. This was pretty misleading in the code snippet from docs:
> 
> > POLYMARKET_PROXY_ADDRESS: str = '' #This is the address you deposit/send USDC to to FUND your Polymarket account.
> 
> I am 100% certain that it is NOT the USDC address that used to fund my account, I checked in transactions, and also checked when clicking "deposit" button in polymarket, it shows different address than the one displayed on the top right, aka profile address.
> 
> Hope this helps!

THIS WORKED!!!

I couldn't find this address for some reason in my settings or my magic link page. I had to go to the Network Tab in Inspect Element of the Browser to get it. Admins really need to update the docs. Struggled for 2+ days trying to find this address.

**Comment by anitas2869-pixel** [comment]
ur actual proxy wallet is here guys https://polymarket.com/settings
